version: "3.8"

services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:7000"
  mongodb:
    container_name: mongodb
    image: mongo
    user: root:root
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db